source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'ModulePullRefresh_Example' do
	pod 'ModulePullRefresh', :path => '../'
	pod 'LYCategory'

	target 'ModulePullRefresh_Tests' do
		inherit! :search_paths
	end
end
