source 'https://github.com/blodely/LYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ModulePullRefresh_Example' do
  pod 'ModulePullRefresh', :path => '../'
  
  pod 'LYCategory', '~> 1.2.4'

  target 'ModulePullRefresh_Tests' do
    inherit! :search_paths

    
  end
end
