source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'ModulePullRefresh_Example' do
	pod 'ModulePullRefresh', :path => '../'
	pod 'LYCategory'

	target 'ModulePullRefresh_Tests' do
		inherit! :search_paths
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
			end
		end
	end
end
